### PR TITLE
Create Bicubic shaders mcpe

### PR DESCRIPTION
**Pull request by SteveAlexM**
By SteveAlexM

### CODE REVIEW

**Comment by Trashy7313** [comment]
how i download ;-;

**Comment by SteveAlexM** [comment]
click this linkhttps://
github.com/SteveAlexM/bicubic-shaders-be/releases/tag/3.1

**Comment by SteveAlexM** [comment]
click this link
https://github.com/SteveAlexM/bicubic-shaders-be/releases/tag/3.1

Pada tanggal Sel, 22 Jun 2021 10:47, Steve AlexM ***@***.***>
menulis:

**Comment by zeng-zeng367** [comment]
I found that after installing Bicubic, nothing is displayed, but other lights and shadows are fine, (device Snapdragon870) (Adreno 650)

**Pull request closed without merging**
